config/routes.rb
Rails.application.routes.draw do
	root to: 'books#top'
	get 'books' => 'books#index',as: "books"
	get 'books/:id' => 'books#show',as:'book'
	get 'books/:id/edit' => 'books#edit',as:'edit_book'
	post 'books' => 'books#create'
	patch 'books/:id' => 'books#update',as: 'update_book'
	delete 'books/:id' => 'books#destroy',as: 'destroy_book'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	validates :title, presence: true
	validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def top
  end

  def index
  	@books = Book.all
  	@book = Book.new
  end

  def show
  	@book = Book.find(params[:id])
  end

  def edit
  	@book = Book.find(params[:id])
  end

  def create
  	@book = Book.new(book_params)
      if @book.save
        flash[:notice] = "Book was successfully created."
          redirect_to book_path(@book.id)
      else
        @books = Book.all
        render :index
      end
  end

  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
    flash[:notice] = "Book was successfully updated."
  	redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
  	book = Book.find(params[:id])
  	if book.destroy
          flash[:notice] = "Book was successfully destroyed."
    	redirect_to "/books"
    else
      @books = Book.all
      render :index
    end
  end

  private

  def book_params
  	params.require(:book).permit(:title,:body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<% if @book.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>


<%= form_for(@book, url:"/books/#{@book.id}") do |f| %>


    <p>title</p>
    <%= f.text_field :title %>
    <p>Body</p>
    <%= f.text_area :body %>
    <p><%= f.submit 'Update Book' %></p>
<% end %>

<%= link_to 'show', book_path(@book.id)%><span> | </span><%= link_to 'back', "/books"%>

app/views/books/index.html.erb
<% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>

<h1>Books</h1>
<table>
	<thead>
		<tr>
			<th>Title</th>
			<th>Body</th>
		</tr>
	</thead>
	<tbody>
		<% @books.each do |book| %>
		<tr>
			<td><%= book.title %></td>
			<td><%= book.body %></td>
			<td><%= link_to 'show', book_path(book.id)%></td>
			<td><%= link_to 'edit', edit_book_path(book.id)%></td>
			<td><%= link_to 'destroy', destroy_book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %></td>
		</tr>
		<% end %>
	</tbody>
</table>
<h2>new book</h2>

<% if @book.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>


<%= form_for @book, :url => {:action => :create} do |f| %>
<p>Title</p>
 <%= f.text_field :title %>
<p>Body</p>
    <%= f.text_area :body %>
<p></p>
 <%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>
<h2>タイトル</h2>
<p><%= @book.title %></p>
<h2>本文</h2>
<p><%= @book.body %></p>
<p><%= link_to 'edit', edit_book_path(@book.id)%></p>
<p><%= link_to 'back', "/books"%></p>

app/views/books/top.html.erb
<h1>ようこそ　Bookerへ！</h1>
<p>Bookers では、さまざまな書籍に関するあなたの意見や</p>

<p>印象を共有し交換することができます。</p>


<%= link_to 'Start', "/books" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>